const ACTION_TYPE = {
  PRODUCTS_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCTS_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCTS_LIST_ERROR: 'PRODUCT_LIST_ERROR',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR',
};

export default ACTION_TYPE;